AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Currency Exchange Rate Service
  
  A serverless microservice that provides real-time and cached exchange rates
  through a REST API, implementing Hexagonal Architecture and resilience patterns.

# More values are available inside the context parameter defined
# https://github.com/awslabs/serverless-application-model/blob/master/docs/parameters-and-globals.rst

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO
        POWERTOOLS_SERVICE_NAME: currenseen
        POWERTOOLS_METRICS_NAMESPACE: Currenseen

Resources:
  ExchangeRateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: bootstrap
      Description: Currency Exchange Rate Service Lambda Handler
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Environment:
        Variables:
          # DynamoDB Configuration
          TABLE_NAME: !Ref ExchangeRatesTable
          AWS_REGION: !Ref AWS::Region
          
          # Logging Configuration
          LOG_LEVEL: INFO
          LOG_FORMAT: json
          
          # Cache Configuration
          CACHE_TTL: 1h
          
          # External API Configuration
          EXCHANGE_RATE_API_URL: https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1
          EXCHANGE_RATE_API_TIMEOUT: 10
          EXCHANGE_RATE_API_RETRY_ATTEMPTS: 3
          
          # Circuit Breaker Configuration
          CIRCUIT_BREAKER_FAILURE_THRESHOLD: 5
          CIRCUIT_BREAKER_COOLDOWN_SECONDS: 30
          CIRCUIT_BREAKER_SUCCESS_THRESHOLD: 1
          
          # Secrets Manager Configuration
          SECRETS_MANAGER_SECRET_NAME: !Sub '${Environment}/currenseen/api-keys'
          SECRETS_MANAGER_ENABLED: true
          SECRETS_MANAGER_CACHE_TTL: 5m
          
          # Rate Limiting Configuration
          RATE_LIMIT_REQUESTS_PER_MINUTE: 100
          RATE_LIMIT_BURST_SIZE: 10
          RATE_LIMIT_ENABLED: true
      Events:
        GetRate:
          Type: Api
          Properties:
            RestApiId: !Ref ExchangeRateApi
            Path: /rates/{base}/{target}
            Method: GET
        GetAllRates:
          Type: Api
          Properties:
            RestApiId: !Ref ExchangeRateApi
            Path: /rates/{base}
            Method: GET
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref ExchangeRateApi
            Path: /health
            Method: GET
      Policies:
        # DynamoDB: Read and write access to exchange rates table
        - DynamoDBCrudPolicy:
            TableName: !Ref ExchangeRatesTable
        # Secrets Manager: Read-only access to API keys secret
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !GetAtt ApiKeySecret.Arn
        # CloudWatch Logs: Write access for logging (least privilege)
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*'
      Layers:
        # Lambda Layer for Go runtime will be added here
        # Example: - !Ref GoRuntimeLayer

  ExchangeRateApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'300'"
      Auth:
        ApiKeyRequired: false  # We handle API key validation in Lambda, not API Gateway
      # Throttling configuration
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      # Default route throttling
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
        ThrottlingRateLimit: 100
      DefinitionBody:
        swagger: "2.0"
        info:
          title: Currency Exchange Rate API
          version: "1.0"
        paths:
          /rates/{base}/{target}:
            get:
              summary: Get exchange rate for currency pair
              parameters:
                - name: base
                  in: path
                  required: true
                  type: string
                  description: Base currency code (ISO 4217)
                - name: target
                  in: path
                  required: true
                  type: string
                  description: Target currency code (ISO 4217)
              responses:
                '200':
                  description: Success
                '400':
                  description: Bad Request
                '404':
                  description: Not Found
                '500':
                  description: Internal Server Error
          /rates/{base}:
            get:
              summary: Get all rates for base currency
              parameters:
                - name: base
                  in: path
                  required: true
                  type: string
                  description: Base currency code (ISO 4217)
              responses:
                '200':
                  description: Success
                '400':
                  description: Bad Request
                '500':
                  description: Internal Server Error
          /health:
            get:
              summary: Health check endpoint
              responses:
                '200':
                  description: Service is healthy

  ExchangeRatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ExchangeRates
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: BaseCurrency
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: BaseCurrencyIndex
          KeySchema:
            - AttributeName: BaseCurrency
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: TTL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Project
          Value: Currenseen
        - Key: Environment
          Value: !Ref Environment

  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Environment}/currenseen/api-keys'
      Description: API keys for Currency Exchange Rate Service
      GenerateSecretString:
        SecretStringTemplate: '{"api-key": ""}'
        GenerateStringKey: api-key
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # CloudWatch Log Group for Lambda function
  ExchangeRateFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ExchangeRateFunction}'
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: Currenseen
        - Key: Environment
          Value: !Ref Environment
    DependsOn: ExchangeRateFunction

Outputs:
  ExchangeRateApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ExchangeRateApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  ExchangeRateFunction:
    Description: "Exchange Rate Lambda Function ARN"
    Value: !GetAtt ExchangeRateFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"
  ExchangeRatesTable:
    Description: "DynamoDB Table Name"
    Value: !Ref ExchangeRatesTable
    Export:
      Name: !Sub "${AWS::StackName}-TableName"
  ApiKeySecretArn:
    Description: "Secrets Manager Secret ARN for API Keys"
    Value: !GetAtt ApiKeySecret.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SecretArn"

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)

